"""Add core models: Approval, AuditEntry, WorkflowRun

Revision ID: f3b14e13ca3c
Revises: 
Create Date: 2026-03-26 14:26:41.291559
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = 'f3b14e13ca3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=255), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_expires_at'), 'approvals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_workflow_id'), 'approvals', ['workflow_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entries_actor'), 'audit_entries', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_entries_workflow_id'), 'audit_entries', ['workflow_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_audit_entries_workflow_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_approvals_workflow_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_expires_at'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
